bracketSpacing: true
printWidth: 100
semi: false
singleQuote: true
tabWidth: 2
trailingComma: all
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
htmlWhitespaceSensitivity: ignore
